name: ivc_launcher
version: 0.1.7
publish_to: none

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  archive: ^3.6.1
  github: ^9.24.0
  logging: ^1.2.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
