name: Build and Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            output-name: linux_launcher
            binary-dir-name: linux
          - os: windows-latest
            output-name: windows_launcher.exe
            binary-dir-name: windows

    runs-on: ${{ matrix.os }}
    env:
      RELEASE_DIR: Anaam-Launcher-${{ github.ref_name }}-${{ matrix.binary-dir-name }}

    steps:
      - uses: actions/checkout@v4

      - name: Dart Setup
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.3
          
      - name: Install Dependecies
        run: dart pub get
      
      - name: Build for ${{ matrix.os }}
        run: |
          dart compile exe \
          --define=BASE_PATH=${{ vars.BASE_PATH }}\
          --define=API_REPO=${{ vars.API_REPO }}\
          --define=API_OWNER=${{ vars.API_OWNER }}\
          --define=CLIENT_REPO=${{ vars.CLIENT_REPO }}\
          --define=CLIENT_OWNER=${{ vars.CLIENT_OWNER }}\
          --define=GITHUB_TOKEN=${{ secrets.REPO_ACCESS_PAT }}\
          bin/ivc_launcher.dart -o ${{ env.RELEASE_DIR }}/${{ matrix.output-name }}

      - name: Create Release Archive
        uses: ihiroky/archive-action@v1
        with:
          root_dir: ${{ env.RELEASE_DIR }} 
          file_path: ${{ env.RELEASE_DIR }}.zip
          verbose: true

      - name: List Directory Tree
        run: ls -R

      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ${{ env.RELEASE_DIR }}.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        
      - name: Display directory structure
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/*.zip